-- INSERT INTO provinces (id, name) VALUES (%s, %s);...
-- INSERT INTO provinces (id, name) VALUES (%s, %s);...
-- INSERT INTO provinces (id, name) VALUES (%s, %s);...
-- INSERT INTO provinces (id, name) VALUES (%s, %s);...
-- INSERT INTO provinces (id, name) VALUES (%s, %s);...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO districts (id, name, province_id) VALU...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO schools (id, name, district_id, type) ...
-- INSERT INTO school_types (id, name, abbreviation, ...
-- INSERT INTO school_types (id, name, abbreviation, ...
-- INSERT INTO school_types (id, name, abbreviation, ...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO trades (id, name, category) VALUES (%s...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO school_trades (id, school_id, trade_id...
-- INSERT INTO users (id, username, password_hash, ro...
-- INSERT INTO users (id, username, password_hash, ro...
-- INSERT INTO users (id, username, password_hash, ro...
-- INSERT INTO users (id, username, password_hash, ro...
-- INSERT INTO users (id, username, password_hash, ro...
-- INSERT INTO users (id, username, password_hash, ro...
-- INSERT INTO questions (id, question_text, question...
-- INSERT INTO questions (id, question_text, question...
-- INSERT INTO questions (id, question_text, question...
-- INSERT INTO quizzes (id, title, description, sched...
-- INSERT INTO quiz_questions (id, quiz_id, question_...
-- INSERT INTO quiz_questions (id, quiz_id, question_...
-- INSERT INTO quiz_questions (id, quiz_id, question_...
