// Icon mapping for emoji replacement
export const iconMap = {
  '✅': 'CheckCircle',
  '❌': 'XCircle',
  '📚': 'BookOpen',
  '👥': 'Users',
  '📊': 'BarChart',
  '📄': 'FileText',
  '🎯': 'Target',
  '⚙️': 'Settings',
  '📋': 'ClipboardList',
  '🔧': 'Wrench',
  '📤': 'Upload',
  '📥': 'Download',
  '🚀': 'Rocket',
  '💾': 'Save',
  '🔍': 'Search',
  '➕': 'Plus',
  '✏️': 'Edit',
  '🗑️': 'Trash2',
  '📡': 'Radio',
  '⏳': 'Clock',
  '🔐': 'Lock',
  '🔑': 'Key',
  '📝': 'FileEdit',
  '🎓': 'GraduationCap',
  '🏆': 'Trophy',
  '⭐': 'Star',
  '🔔': 'Bell',
  '📅': 'Calendar',
  '⏰': 'AlarmClock',
  '🤖': 'Bot'
};
